import type { ImportQuickLearningItemsInput } from "./learning.contract";

const templateItems = [
    {
      topic: "01. Advantages & Disadvantages — Lợi ích và bất lợi",
      prompt: "Mở bài: giới thiệu một xu hướng ngày càng phổ biến.",
      answer: "Nowadays, TOPIC is becoming increasingly common in many countries.",
      context: "Thay TOPIC bằng cụm danh từ, ví dụ: online learning hoặc the use of public transport.",
    },
    {
      topic: "01. Advantages & Disadvantages — Lợi ích và bất lợi",
      prompt: "Thesis: báo trước bài sẽ phân tích cả lợi ích và bất lợi.",
      answer: "Although TOPIC offers several significant benefits, it also presents certain disadvantages.",
      context: "Câu thesis B2 cho dạng Advantages and Disadvantages.",
    },
    {
      topic: "01. Advantages & Disadvantages — Lợi ích và bất lợi",
      prompt: "Mở thân bài 1: giới thiệu nhóm lợi ích.",
      answer: "On the one hand, TOPIC offers a number of important advantages.",
      context: "Sau câu này, triển khai hai lợi ích bằng C-M-E-L.",
    },
    {
      topic: "01. Advantages & Disadvantages — Lợi ích và bất lợi",
      prompt: "C-M-E-L: nêu và phát triển một lợi ích.",
      answer: "One major advantage is that CLAIM. This is mainly because MECHANISM. For example, EXAMPLE. As a result, RESULT.",
      context: "CLAIM = ý chính; MECHANISM = giải thích; EXAMPLE = ví dụ; RESULT = kết quả.",
    },
    {
      topic: "01. Advantages & Disadvantages — Lợi ích và bất lợi",
      prompt: "Mở thân bài 2: chuyển sang nhóm bất lợi.",
      answer: "On the other hand, TOPIC also has several disadvantages that should be considered.",
      context: "Dùng để mở đoạn bất lợi và tạo đối lập với thân bài 1.",
    },
    {
      topic: "01. Advantages & Disadvantages — Lợi ích và bất lợi",
      prompt: "Kết bài: tóm tắt hai mặt và đưa khuyến nghị.",
      answer: "In conclusion, TOPIC has both benefits and drawbacks. Therefore, people should maximise its advantages while reducing its negative effects.",
      context: "Không thêm ý chính mới trong kết bài.",
    },
    {
      topic: "02. Agree or Disagree — Đồng ý hoặc phản đối",
      prompt: "Mở bài: giới thiệu một nhận định đang được tranh luận.",
      answer: "It is often argued that STATEMENT.",
      context: "Thay STATEMENT bằng mệnh đề được paraphrase từ đề bài.",
    },
    {
      topic: "02. Agree or Disagree — Đồng ý hoặc phản đối",
      prompt: "Thesis: thể hiện đồng ý hoàn toàn và báo trước hai lý do.",
      answer: "I completely agree with this view because REASON 1 and REASON 2.",
      context: "Nếu phản đối, đổi agree thành disagree và thay hai lý do.",
    },
    {
      topic: "02. Agree or Disagree — Đồng ý hoặc phản đối",
      prompt: "Mở thân bài 1: đưa ra lý do đầu tiên cho quan điểm.",
      answer: "The first reason why I support this view is that REASON 1.",
      context: "Sau đó giải thích bằng This is mainly because... và thêm ví dụ.",
    },
    {
      topic: "02. Agree or Disagree — Đồng ý hoặc phản đối",
      prompt: "Mở thân bài 2: đưa ra lý do thứ hai.",
      answer: "Another important reason is that REASON 2.",
      context: "Phát triển lý do bằng mechanism, example và result.",
    },
    {
      topic: "02. Agree or Disagree — Đồng ý hoặc phản đối",
      prompt: "Phản biện ngắn một ý kiến đối lập.",
      answer: "Admittedly, some people argue that OPPOSING VIEW. However, this argument is less convincing because REFUTATION.",
      context: "Thừa nhận ý đối lập trước, sau đó chỉ ra giới hạn của nó.",
    },
    {
      topic: "02. Agree or Disagree — Đồng ý hoặc phản đối",
      prompt: "Kết bài: khẳng định lại quan điểm và hai lý do.",
      answer: "In conclusion, I firmly believe that POSITION because REASON 1 and REASON 2.",
      context: "POSITION phải nhất quán với thesis ở mở bài.",
    },
    {
      topic: "03. Balanced Opinion — Đồng ý một phần",
      prompt: "Mở bài: cho biết nhận định chỉ đúng trong một số trường hợp.",
      answer: "Although this view is valid to some extent, it should not be applied in every situation.",
      context: "Dùng khi câu trả lời phụ thuộc đối tượng hoặc hoàn cảnh.",
    },
    {
      topic: "03. Balanced Opinion — Đồng ý một phần",
      prompt: "Thesis: chấp nhận phía A nhưng nghiêng về phía B.",
      answer: "While I accept that SIDE A, I believe that SIDE B is generally more appropriate.",
      context: "SIDE A và SIDE B phải là hai mệnh đề hoàn chỉnh.",
    },
    {
      topic: "03. Balanced Opinion — Đồng ý một phần",
      prompt: "Mở thân bài 1: giải thích khi nào phía A hợp lý.",
      answer: "On the one hand, SIDE A can be beneficial when CONDITION A.",
      context: "Nêu rõ đối tượng hoặc điều kiện mà phía A có hiệu quả.",
    },
    {
      topic: "03. Balanced Opinion — Đồng ý một phần",
      prompt: "Mở thân bài 2: trình bày quan điểm chính của mình.",
      answer: "On the other hand, I believe that SIDE B is more suitable in most cases.",
      context: "Đây là phía cần được phát triển và đánh giá mạnh hơn.",
    },
    {
      topic: "03. Balanced Opinion — Đồng ý một phần",
      prompt: "Kết bài: đưa ra phán đoán có điều kiện.",
      answer: "In conclusion, although SIDE A can be useful in certain situations, SIDE B is preferable when CONDITION B.",
      context: "Không kết luận tuyệt đối nếu thesis đã chọn quan điểm cân bằng.",
    },
    {
      topic: "04. Outweigh — Lợi ích có lớn hơn bất lợi?",
      prompt: "Thesis: khẳng định lợi ích lớn hơn bất lợi.",
      answer: "Despite several potential drawbacks, I believe that the benefits of TOPIC are far more significant.",
      context: "Có thể đảo benefits và drawbacks nếu chọn quan điểm ngược lại.",
    },
    {
      topic: "04. Outweigh — Lợi ích có lớn hơn bất lợi?",
      prompt: "Mở thân bài 1: thừa nhận phía yếu hơn.",
      answer: "Admittedly, TOPIC has some disadvantages, the most serious of which is DRAWBACK.",
      context: "Đặt phía yếu hơn trước để dành thân bài 2 cho phía bạn ủng hộ.",
    },
    {
      topic: "04. Outweigh — Lợi ích có lớn hơn bất lợi?",
      prompt: "Đánh giá rằng bất lợi có thể kiểm soát được.",
      answer: "However, these problems are generally manageable if SOLUTION is implemented effectively.",
      context: "Câu này giúp so sánh, thay vì chỉ liệt kê hai phía.",
    },
    {
      topic: "04. Outweigh — Lợi ích có lớn hơn bất lợi?",
      prompt: "Mở thân bài 2: chuyển sang phía mạnh hơn.",
      answer: "Nevertheless, the advantages of TOPIC are more substantial and long-lasting.",
      context: "Sau đó phát triển hai lợi ích quan trọng nhất.",
    },
    {
      topic: "04. Outweigh — Lợi ích có lớn hơn bất lợi?",
      prompt: "Câu so sánh quyết định giữa lợi ích và bất lợi.",
      answer: "Unlike the drawbacks, these benefits affect more people and produce longer-term results.",
      context: "Có thể đổi tiêu chí thành wider impact, essential need hoặc irreversible effect.",
    },
    {
      topic: "04. Outweigh — Lợi ích có lớn hơn bất lợi?",
      prompt: "Kết bài: trả lời trực tiếp câu hỏi outweigh.",
      answer: "In conclusion, although TOPIC may cause certain problems, its advantages clearly outweigh its disadvantages.",
      context: "Bắt buộc phải nói rõ bên nào lớn hơn trong kết bài.",
    },
    {
      topic: "05. Discuss Both Views — Thảo luận hai quan điểm",
      prompt: "Mở bài: giới thiệu hai quan điểm trái chiều.",
      answer: "Some people believe that VIEW A, while others argue that VIEW B.",
      context: "VIEW A và VIEW B phải phản ánh đúng hai quan điểm trong đề.",
    },
    {
      topic: "05. Discuss Both Views — Thảo luận hai quan điểm",
      prompt: "Thesis: báo trước thảo luận hai phía và nêu quan điểm.",
      answer: "This essay will discuss both perspectives before explaining why I support VIEW B.",
      context: "Có thể đổi VIEW B thành VIEW A theo quan điểm của bạn.",
    },
    {
      topic: "05. Discuss Both Views — Thảo luận hai quan điểm",
      prompt: "Mở thân bài 1: trình bày công bằng quan điểm A.",
      answer: "On the one hand, supporters of VIEW A argue that REASON A.",
      context: "Không phản bác ngay; hãy giải thích và cho ví dụ trước.",
    },
    {
      topic: "05. Discuss Both Views — Thảo luận hai quan điểm",
      prompt: "Mở thân bài 2: trình bày quan điểm B.",
      answer: "On the other hand, those who favour VIEW B point out that REASON B.",
      context: "Sau khi trình bày, giải thích tại sao bạn thấy phía này thuyết phục hơn.",
    },
    {
      topic: "05. Discuss Both Views — Thảo luận hai quan điểm",
      prompt: "Đánh giá quan điểm mình lựa chọn.",
      answer: "I find this view more convincing because DECISIVE REASON.",
      context: "DECISIVE REASON nên là tiêu chí so sánh rõ ràng.",
    },
    {
      topic: "05. Discuss Both Views — Thảo luận hai quan điểm",
      prompt: "Kết bài: công nhận cả hai nhưng chọn một phía.",
      answer: "In conclusion, both views have some merit, but I believe that PREFERRED VIEW is more convincing.",
      context: "Không đưa thêm luận điểm mới trong câu này.",
    },
    {
      topic: "06. Causes & Effects — Nguyên nhân và hệ quả",
      prompt: "Mở bài: giới thiệu một xu hướng hoặc vấn đề phổ biến.",
      answer: "Nowadays, PROBLEM is becoming increasingly common in many countries.",
      context: "PROBLEM là danh từ hoặc cụm danh từ.",
    },
    {
      topic: "06. Causes & Effects — Nguyên nhân và hệ quả",
      prompt: "Thesis: báo trước phân tích nguyên nhân và hệ quả.",
      answer: "This essay will examine the main causes of PROBLEM and its effects on individuals and society.",
      context: "Không đổi effects thành solutions nếu đề không hỏi giải pháp.",
    },
    {
      topic: "06. Causes & Effects — Nguyên nhân và hệ quả",
      prompt: "Mở thân bài 1: giới thiệu nhóm nguyên nhân.",
      answer: "A number of factors contribute to PROBLEM.",
      context: "Sau đó nêu một nguyên nhân chính và một yếu tố góp phần.",
    },
    {
      topic: "06. Causes & Effects — Nguyên nhân và hệ quả",
      prompt: "Mở thân bài 2: giới thiệu nhóm hệ quả.",
      answer: "PROBLEM can have several serious consequences for both individuals and society.",
      context: "Có thể chia immediate effect và long-term effect.",
    },
    {
      topic: "06. Causes & Effects — Nguyên nhân và hệ quả",
      prompt: "Kết bài: tóm tắt nguyên nhân và hệ quả.",
      answer: "In conclusion, PROBLEM is mainly caused by CAUSES and can lead to EFFECTS.",
      context: "Chỉ tóm tắt nội dung đã phân tích.",
    },
    {
      topic: "07. Causes & Solutions — Nguyên nhân và giải pháp",
      prompt: "Mở bài: giới thiệu một vấn đề cần được giải quyết.",
      answer: "PROBLEM has become a growing concern in many parts of the world.",
      context: "Có thể thay growing concern bằng serious issue.",
    },
    {
      topic: "07. Causes & Solutions — Nguyên nhân và giải pháp",
      prompt: "Thesis: báo trước phân tích nguyên nhân và giải pháp.",
      answer: "This essay will identify the main causes of PROBLEM and suggest several practical solutions.",
      context: "Hai đoạn thân bài phải lần lượt trả lời causes và solutions.",
    },
    {
      topic: "07. Causes & Solutions — Nguyên nhân và giải pháp",
      prompt: "Mở thân bài 1: giới thiệu các yếu tố gây ra vấn đề.",
      answer: "There are two main factors responsible for PROBLEM.",
      context: "Phát triển mỗi nguyên nhân bằng mechanism và result.",
    },
    {
      topic: "07. Causes & Solutions — Nguyên nhân và giải pháp",
      prompt: "Mở thân bài 2: giới thiệu các biện pháp xử lý.",
      answer: "Several practical measures can be taken to address these causes.",
      context: "Mỗi giải pháp phải khớp trực tiếp với một nguyên nhân.",
    },
    {
      topic: "07. Causes & Solutions — Nguyên nhân và giải pháp",
      prompt: "Phát triển giải pháp theo Actor-Action-Mechanism-Outcome.",
      answer: "ACTOR should take ACTION. This would address CAUSE by MECHANISM, thereby producing OUTCOME.",
      context: "Kiểm tra actor có đủ khả năng thực hiện action hay không.",
    },
    {
      topic: "07. Causes & Solutions — Nguyên nhân và giải pháp",
      prompt: "Kết bài: tóm tắt nguyên nhân và biện pháp.",
      answer: "In conclusion, PROBLEM stems mainly from CAUSES, but it can be reduced through SOLUTIONS.",
      context: "Có thể thêm một câu kêu gọi phối hợp giữa các chủ thể.",
    },
    {
      topic: "08. Problems & Solutions — Vấn đề và giải pháp",
      prompt: "Mở bài: nêu rằng chủ đề tạo ra nhiều vấn đề nghiêm trọng.",
      answer: "In recent years, TOPIC has created a number of serious concerns.",
      context: "TOPIC là hiện tượng; problems là hậu quả/vấn đề do hiện tượng đó gây ra.",
    },
    {
      topic: "08. Problems & Solutions — Vấn đề và giải pháp",
      prompt: "Thesis: báo trước phân tích vấn đề và đề xuất giải pháp.",
      answer: "This essay will discuss the main problems associated with TOPIC and propose several effective solutions.",
      context: "Không nhầm problems với causes.",
    },
    {
      topic: "08. Problems & Solutions — Vấn đề và giải pháp",
      prompt: "Mở thân bài 1: giới thiệu các vấn đề do chủ đề gây ra.",
      answer: "TOPIC gives rise to several significant problems.",
      context: "Có thể thay gives rise to bằng causes hoặc results in.",
    },
    {
      topic: "08. Problems & Solutions — Vấn đề và giải pháp",
      prompt: "Mở thân bài 2: giới thiệu giải pháp cho các vấn đề.",
      answer: "There are several possible ways to tackle these problems.",
      context: "Dùng To deal with PROBLEM 1... và Another solution is... để triển khai.",
    },
    {
      topic: "08. Problems & Solutions — Vấn đề và giải pháp",
      prompt: "Kết bài: khẳng định các vấn đề có thể được giảm bớt.",
      answer: "In conclusion, TOPIC causes serious problems, but these can be addressed through coordinated action.",
      context: "Có thể nêu lại ngắn gọn hai giải pháp chính.",
    },
    {
      topic: "09. Effects & Solutions — Hệ quả và giải pháp",
      prompt: "Mở bài: nêu vấn đề có ảnh hưởng nghiêm trọng.",
      answer: "PROBLEM is becoming increasingly serious and can have harmful effects on society.",
      context: "Có thể thay society bằng individuals, young people hoặc the environment.",
    },
    {
      topic: "09. Effects & Solutions — Hệ quả và giải pháp",
      prompt: "Thesis: báo trước phân tích hệ quả và cách giảm chúng.",
      answer: "This essay will discuss the main consequences of PROBLEM and suggest several measures to reduce them.",
      context: "them thay cho consequences, không thay cho problem.",
    },
    {
      topic: "09. Effects & Solutions — Hệ quả và giải pháp",
      prompt: "Mở thân bài 1: giới thiệu nhóm hệ quả.",
      answer: "The effects of PROBLEM can be seen at both individual and societal levels.",
      context: "Có thể chia đoạn thành tác động trực tiếp và tác động dài hạn.",
    },
    {
      topic: "09. Effects & Solutions — Hệ quả và giải pháp",
      prompt: "Mở thân bài 2: giới thiệu giải pháp giảm tác động.",
      answer: "Several actions can be taken to limit these negative effects.",
      context: "Giải thích mỗi action giúp giảm effect nào và bằng cách nào.",
    },
    {
      topic: "09. Effects & Solutions — Hệ quả và giải pháp",
      prompt: "Kết bài: tóm tắt hệ quả và khẳng định có thể kiểm soát.",
      answer: "In conclusion, PROBLEM has serious consequences, but its impact can be limited through appropriate measures.",
      context: "Không đưa nguyên nhân mới vào kết bài nếu đề chỉ hỏi effects và solutions.",
    },
    {
      topic: "10. One-sided Question — Đề chỉ hỏi một mặt",
      prompt: "Thesis khi đề chỉ hỏi nguyên nhân.",
      answer: "This trend can be explained by a combination of personal and social factors.",
      context: "Body 1 viết nguyên nhân cá nhân; Body 2 viết nguyên nhân xã hội.",
    },
    {
      topic: "10. One-sided Question — Đề chỉ hỏi một mặt",
      prompt: "Thesis khi đề chỉ hỏi hệ quả.",
      answer: "The consequences of this trend can be seen at both individual and societal levels.",
      context: "Body 1 viết immediate effects; Body 2 viết long-term effects.",
    },
    {
      topic: "10. One-sided Question — Đề chỉ hỏi một mặt",
      prompt: "Thesis khi đề chỉ hỏi giải pháp.",
      answer: "Addressing this issue requires both institutional action and changes in individual behaviour.",
      context: "Body 1 viết giải pháp tổ chức; Body 2 viết giải pháp cá nhân.",
    },
    {
      topic: "10. One-sided Question — Đề chỉ hỏi một mặt",
      prompt: "Thesis khi đề chỉ hỏi lợi ích hoặc tầm quan trọng.",
      answer: "TOPIC plays an important role in modern life and provides significant benefits for TARGET GROUP.",
      context: "Chia hai đoạn thân bài theo hai nhóm lợi ích, không viết bất lợi.",
    },
    {
      topic: "10. One-sided Question — Đề chỉ hỏi một mặt",
      prompt: "Nguyên tắc quan trọng khi đề chỉ hỏi một mặt.",
      answer: "Both body paragraphs must directly answer the single task stated in the question.",
      context: "Không tự thêm causes, effects hoặc solutions nếu đề không yêu cầu.",
    },
];

const applicationPromptByAnswer: Record<string, string> = {
  "Nowadays, TOPIC is becoming increasingly common in many countries.": "Ngày nay, học trực tuyến đang trở nên ngày càng phổ biến ở nhiều quốc gia.",
  "Although TOPIC offers several significant benefits, it also presents certain disadvantages.": "Mặc dù học trực tuyến mang lại một số lợi ích đáng kể, nó cũng có những bất lợi nhất định.",
  "On the one hand, TOPIC offers a number of important advantages.": "Một mặt, học trực tuyến mang lại một số lợi ích quan trọng.",
  "One major advantage is that CLAIM. This is mainly because MECHANISM. For example, EXAMPLE. As a result, RESULT.": "Một lợi ích lớn là học trực tuyến đem lại sự linh hoạt. Điều này chủ yếu là vì người học có thể học vào thời gian và địa điểm thuận tiện. Ví dụ, nhân viên toàn thời gian có thể học vào buổi tối. Nhờ đó, họ có thể tiếp tục học mà không phải nghỉ việc.",
  "On the other hand, TOPIC also has several disadvantages that should be considered.": "Mặt khác, học trực tuyến cũng có một số bất lợi cần được cân nhắc.",
  "In conclusion, TOPIC has both benefits and drawbacks. Therefore, people should maximise its advantages while reducing its negative effects.": "Tóm lại, học trực tuyến có cả lợi ích và hạn chế. Vì vậy, chúng ta nên phát huy ưu điểm đồng thời giảm thiểu những tác động tiêu cực của nó.",
  "It is often argued that STATEMENT.": "Người ta thường cho rằng trẻ em nên bắt đầu học ngoại ngữ từ bậc tiểu học.",
  "I completely agree with this view because REASON 1 and REASON 2.": "Tôi hoàn toàn đồng ý với quan điểm này vì trẻ nhỏ tiếp thu cách phát âm nhanh hơn và ít ngại mắc lỗi khi giao tiếp.",
  "The first reason why I support this view is that REASON 1.": "Lý do đầu tiên khiến tôi ủng hộ quan điểm này là trẻ nhỏ có thể tiếp thu cách phát âm nhanh hơn.",
  "Another important reason is that REASON 2.": "Một lý do quan trọng khác là trẻ em thường ít ngại mắc lỗi khi giao tiếp.",
  "Admittedly, some people argue that OPPOSING VIEW. However, this argument is less convincing because REFUTATION.": "Phải thừa nhận rằng một số người cho rằng chương trình học của trẻ đã quá nặng. Tuy nhiên, lập luận này kém thuyết phục hơn vì ngoại ngữ có thể được dạy thông qua các hoạt động vui nhộn.",
  "In conclusion, I firmly believe that POSITION because REASON 1 and REASON 2.": "Tóm lại, tôi tin chắc rằng trẻ em nên học ngoại ngữ từ bậc tiểu học vì chúng tiếp thu cách phát âm nhanh hơn và tự tin giao tiếp hơn.",
  "Although this view is valid to some extent, it should not be applied in every situation.": "Mặc dù quan điểm cho rằng mọi người nên học đại học đúng ở một mức độ nào đó, nó không nên được áp dụng trong mọi trường hợp.",
  "While I accept that SIDE A, I believe that SIDE B is generally more appropriate.": "Mặc dù tôi thừa nhận đại học cần thiết đối với những nghề đòi hỏi kiến thức chuyên sâu, tôi tin rằng học nghề thường phù hợp hơn với người muốn đi làm sớm.",
  "On the one hand, SIDE A can be beneficial when CONDITION A.": "Một mặt, học đại học có thể hữu ích khi một nghề nghiệp đòi hỏi kiến thức học thuật chuyên sâu.",
  "On the other hand, I believe that SIDE B is more suitable in most cases.": "Mặt khác, tôi tin rằng học nghề phù hợp hơn trong phần lớn trường hợp đối với những người muốn có kỹ năng thực tế.",
  "In conclusion, although SIDE A can be useful in certain situations, SIDE B is preferable when CONDITION B.": "Tóm lại, mặc dù đại học có thể hữu ích trong một số trường hợp, học nghề là lựa chọn tốt hơn khi một người muốn đi làm sớm.",
  "Despite several potential drawbacks, I believe that the benefits of TOPIC are far more significant.": "Mặc dù có một số bất lợi tiềm ẩn, tôi tin rằng lợi ích của việc du học lớn hơn nhiều.",
  "Admittedly, TOPIC has some disadvantages, the most serious of which is DRAWBACK.": "Phải thừa nhận rằng du học có một số bất lợi, trong đó nghiêm trọng nhất là chi phí cao.",
  "However, these problems are generally manageable if SOLUTION is implemented effectively.": "Tuy nhiên, những vấn đề này nhìn chung có thể được kiểm soát nếu học bổng và các dịch vụ hỗ trợ được triển khai hiệu quả.",
  "Nevertheless, the advantages of TOPIC are more substantial and long-lasting.": "Tuy vậy, những lợi ích của việc du học đáng kể và lâu dài hơn.",
  "Unlike the drawbacks, these benefits affect more people and produce longer-term results.": "Không giống như những bất lợi, các lợi ích này ảnh hưởng tích cực đến nhiều người hơn và tạo ra kết quả lâu dài hơn.",
  "In conclusion, although TOPIC may cause certain problems, its advantages clearly outweigh its disadvantages.": "Tóm lại, mặc dù du học có thể gây ra một số vấn đề, lợi ích của nó rõ ràng lớn hơn những bất lợi.",
  "Some people believe that VIEW A, while others argue that VIEW B.": "Một số người tin rằng chính phủ nên quyết định chương trình học, trong khi những người khác cho rằng giáo viên nên có nhiều quyền lựa chọn hơn.",
  "This essay will discuss both perspectives before explaining why I support VIEW B.": "Bài viết này sẽ thảo luận cả hai quan điểm trước khi giải thích lý do tôi ủng hộ việc trao nhiều quyền lựa chọn hơn cho giáo viên.",
  "On the one hand, supporters of VIEW A argue that REASON A.": "Một mặt, những người ủng hộ chương trình học do chính phủ quyết định cho rằng cách này bảo đảm tiêu chuẩn chung trên toàn quốc.",
  "On the other hand, those who favour VIEW B point out that REASON B.": "Mặt khác, những người ủng hộ giáo viên tự lựa chọn nội dung chỉ ra rằng giáo viên hiểu rõ năng lực và sở thích của học sinh.",
  "I find this view more convincing because DECISIVE REASON.": "Tôi thấy quan điểm này thuyết phục hơn vì giáo viên có thể điều chỉnh bài học theo nhu cầu thực tế của học sinh.",
  "In conclusion, both views have some merit, but I believe that PREFERRED VIEW is more convincing.": "Tóm lại, cả hai quan điểm đều có điểm hợp lý, nhưng tôi tin rằng giáo viên nên có nhiều quyền lựa chọn hơn trong một khung chương trình quốc gia.",
  "Nowadays, PROBLEM is becoming increasingly common in many countries.": "Ngày nay, việc lựa chọn sống độc thân đang trở nên ngày càng phổ biến ở nhiều quốc gia.",
  "This essay will examine the main causes of PROBLEM and its effects on individuals and society.": "Bài viết này sẽ phân tích những nguyên nhân chính của xu hướng sống độc thân và ảnh hưởng của nó đối với cá nhân và xã hội.",
  "A number of factors contribute to PROBLEM.": "Có một số yếu tố góp phần khiến ngày càng nhiều người lựa chọn sống độc thân.",
  "PROBLEM can have several serious consequences for both individuals and society.": "Xu hướng sống độc thân có thể gây ra một số hệ quả nghiêm trọng cho cả cá nhân và xã hội.",
  "In conclusion, PROBLEM is mainly caused by CAUSES and can lead to EFFECTS.": "Tóm lại, xu hướng sống độc thân chủ yếu xuất phát từ mong muốn tự do cá nhân và áp lực tài chính, đồng thời có thể dẫn đến sự cô đơn và tỷ lệ sinh thấp.",
  "PROBLEM has become a growing concern in many parts of the world.": "Béo phì ở người trẻ đã trở thành một mối lo ngại ngày càng lớn tại nhiều nơi trên thế giới.",
  "This essay will identify the main causes of PROBLEM and suggest several practical solutions.": "Bài viết này sẽ xác định những nguyên nhân chính gây béo phì ở người trẻ và đề xuất một số giải pháp thiết thực.",
  "There are two main factors responsible for PROBLEM.": "Có hai yếu tố chính gây ra tình trạng béo phì ở người trẻ.",
  "Several practical measures can be taken to address these causes.": "Một số biện pháp thiết thực có thể được thực hiện để giải quyết những nguyên nhân này.",
  "ACTOR should take ACTION. This would address CAUSE by MECHANISM, thereby producing OUTCOME.": "Trường học nên cung cấp các bữa ăn lành mạnh. Biện pháp này sẽ giải quyết thói quen ăn uống kém bằng cách giúp học sinh tiếp cận thực phẩm bổ dưỡng, từ đó giảm nguy cơ béo phì.",
  "In conclusion, PROBLEM stems mainly from CAUSES, but it can be reduced through SOLUTIONS.": "Tóm lại, béo phì ở người trẻ chủ yếu bắt nguồn từ đồ ăn nhanh và việc thiếu vận động, nhưng có thể được giảm bớt thông qua chế độ ăn lành mạnh và hoạt động thể chất thường xuyên.",
  "In recent years, TOPIC has created a number of serious concerns.": "Trong những năm gần đây, tình trạng nghiện Internet ở trẻ em đã gây ra một số vấn đề nghiêm trọng.",
  "This essay will discuss the main problems associated with TOPIC and propose several effective solutions.": "Bài viết này sẽ thảo luận những vấn đề chính liên quan đến tình trạng nghiện Internet ở trẻ em và đề xuất một số giải pháp hiệu quả.",
  "TOPIC gives rise to several significant problems.": "Tình trạng nghiện Internet ở trẻ em gây ra một số vấn đề đáng kể.",
  "There are several possible ways to tackle these problems.": "Có một số cách khả thi để giải quyết những vấn đề này.",
  "In conclusion, TOPIC causes serious problems, but these can be addressed through coordinated action.": "Tóm lại, tình trạng nghiện Internet ở trẻ em gây ra những vấn đề nghiêm trọng, nhưng chúng có thể được giải quyết thông qua sự phối hợp giữa gia đình và nhà trường.",
  "PROBLEM is becoming increasingly serious and can have harmful effects on society.": "Tình trạng căng thẳng kéo dài đang trở nên ngày càng nghiêm trọng và có thể gây ra những ảnh hưởng có hại cho xã hội.",
  "This essay will discuss the main consequences of PROBLEM and suggest several measures to reduce them.": "Bài viết này sẽ thảo luận những hệ quả chính của tình trạng căng thẳng kéo dài và đề xuất một số biện pháp để giảm thiểu chúng.",
  "The effects of PROBLEM can be seen at both individual and societal levels.": "Ảnh hưởng của tình trạng căng thẳng kéo dài có thể được nhận thấy ở cả cấp độ cá nhân và xã hội.",
  "Several actions can be taken to limit these negative effects.": "Một số hành động có thể được thực hiện để hạn chế những tác động tiêu cực này.",
  "In conclusion, PROBLEM has serious consequences, but its impact can be limited through appropriate measures.": "Tóm lại, tình trạng căng thẳng kéo dài gây ra những hệ quả nghiêm trọng, nhưng tác động của nó có thể được hạn chế bằng các biện pháp phù hợp.",
  "This trend can be explained by a combination of personal and social factors.": "Xu hướng ngày càng nhiều người sử dụng không gian công cộng có thể được giải thích bởi sự kết hợp giữa các yếu tố cá nhân và xã hội.",
  "The consequences of this trend can be seen at both individual and societal levels.": "Hệ quả của xu hướng này có thể được nhận thấy ở cả cấp độ cá nhân và xã hội.",
  "Addressing this issue requires both institutional action and changes in individual behaviour.": "Việc giải quyết vấn đề thiếu không gian công cộng đòi hỏi cả hành động từ các tổ chức và sự thay đổi trong hành vi cá nhân.",
  "TOPIC plays an important role in modern life and provides significant benefits for TARGET GROUP.": "Không gian công cộng đóng vai trò quan trọng trong cuộc sống hiện đại và mang lại những lợi ích đáng kể cho cư dân thành thị.",
  "Both body paragraphs must directly answer the single task stated in the question.": "Cả hai đoạn thân bài phải trực tiếp trả lời yêu cầu duy nhất được nêu trong đề bài.",
};

export const vstepWritingTemplatePreset = {
  quizType: "TEMPLATE",
  items: templateItems.map((item) => ({
    ...item,
    applicationPromptVi: applicationPromptByAnswer[item.answer] ?? "Hãy viết câu này bằng tiếng Anh.",
  })),
} satisfies ImportQuickLearningItemsInput;
